# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/agency.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'protos/agency.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/agency.proto\x12\x06\x61gency\"\x94\x01\n\rAgencyRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0e\n\x06origin\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\t\x12\x18\n\x10number_of_people\x18\x04 \x01(\x05\x12\x15\n\rinclude_hotel\x18\x05 \x01(\x08\x12\x13\n\x0binclude_car\x18\x06 \x01(\x08\x12\n\n\x02id\x18\x07 \x01(\t\"\x7f\n\x0b\x41gencyReply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rhotel_details\x18\x03 \x01(\t\x12\x13\n\x0b\x63\x61r_details\x18\x04 \x01(\t\x12\x16\n\x0e\x66light_details\x18\x05 \x01(\t\x12\n\n\x02id\x18\x07 \x01(\t2H\n\rAgencyService\x12\x37\n\tBuyTicket\x12\x15.agency.AgencyRequest\x1a\x13.agency.AgencyReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.agency_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENCYREQUEST']._serialized_start=32
  _globals['_AGENCYREQUEST']._serialized_end=180
  _globals['_AGENCYREPLY']._serialized_start=182
  _globals['_AGENCYREPLY']._serialized_end=309
  _globals['_AGENCYSERVICE']._serialized_start=311
  _globals['_AGENCYSERVICE']._serialized_end=383
# @@protoc_insertion_point(module_scope)
